// <auto-generated />
namespace Treinamentos.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddInstrutor_AddInicio_AddFim_ToTurmas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddInstrutor_AddInicio_AddFim_ToTurmas));
        
        string IMigrationMetadata.Id
        {
            get { return "201302042023063_AddInstrutor_AddInicio_AddFim_ToTurmas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
