// <auto-generated />
namespace Treinamentos.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CreateTreinamentos_CreateTurmas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateTreinamentos_CreateTurmas));
        
        string IMigrationMetadata.Id
        {
            get { return "201302041944467_CreateTreinamentos_CreateTurmas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
